# Generated by Django 3.2.15 on 2023-08-29 09:17

from django.db import migrations, transaction
from django.db import models


def calculate_price(apps, schema_editor):
    OrderDetails = apps.get_model('foodcartapp', 'OrderDetails')
    for order_detail in OrderDetails.objects.all():
        try:
            with transaction.atomic():
                order_detail.price = order_detail.product.price * order_detail.quantity
                order_detail.save()
        except Exception as e:
            print(f"Error updating order_detail {order_detail.pk}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='price',
            field=models.DecimalField(default=0, max_digits=10, decimal_places=2),
        ),
        migrations.RunPython(calculate_price),
    ]
