# Generated by Django 3.2.15 on 2023-09-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_alter_orderdetails_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Необработанный', 'Необработанный'), ('Приготовление', 'Приготовление'), ('Доставка', 'Доставка'), ('Завершено', 'Завершено')], default='Необработанный', max_length=14),
        ),
    ]
