# Generated by Django 3.2.15 on 2023-09-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20230902_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Наличными', 'Наличными'), ('Безналичный', 'Безналичный'), ('Безналичный на месте', 'Безналичный на месте')], db_index=True, default='Наличными', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, max_length=300, verbose_name='Комментарии'),
        ),
    ]
