# Generated by Django 3.2.15 on 2023-09-11 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20230904_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='orders',
                                    to='foodcartapp.restaurant',
                                    verbose_name='рестораны'),
        ),
    ]
