# Generated by Django 3.2.15 on 2023-09-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='ширата'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Необработанный', 'Необработанный'), ('Приготовление', 'Приготовление'), ('Доставка', 'Доставка'), ('Завершено', 'Завершено')], db_index=True, default='Необработанный', max_length=14, verbose_name='Статус заказа'),
        ),
    ]
