# Generated by Django 3.2.15 on 2023-09-18 09:34

from django.db import migrations

from star_burger.settings import YANDEX_API_KEY
from star_burger.utils import fetch_coordinates


def calculate_lon_lat_order(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    for order in Order.objects.all():
        lon, lat = fetch_coordinates(YANDEX_API_KEY, order.address)
        order.lon = lon
        order.lat = lat
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20230918_0856'),
    ]

    operations = [
        migrations.RunPython(calculate_lon_lat_order),
    ]
