# Generated by Django 3.2.15 on 2023-09-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20230918_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='долгота')),
                ('lat', models.FloatField(verbose_name='ширата')),
                ('address', models.CharField(db_index=True, max_length=50, verbose_name='адрес')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата создания заказа')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата создания заказа')),
            ],
            options={
                'verbose_name': 'геопозиция',
                'verbose_name_plural': 'геопозиции',
            },
        ),
    ]
