# Generated by Django 3.2.15 on 2024-01-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_geoposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoposition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обнавления заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Наличными', 'Наличными'), ('Безналичный', 'Безналичный'), ('Безналичный на месте', 'Безналичный на месте')], db_index=True, default='не заполнено', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
